---
- name: Deploy Python Flask App Stack
  hosts: 3.208.13.74  # Use the IP address of your swarm manager node
  become: yes

  tasks:
    - name: Remove existing stack (if any)
      command: "docker stack rm python-flask-stack || true"

    - name: Deploy Docker stack
      command: "docker stack deploy -c docker-compose.yml python-flask-stack"
