---
- name: Deploy Python Flask App Stack
  hosts: 18.234.31.112
  become: yes

  tasks:
    - name: Copy docker-compose.yml to swarm manager node
      copy:
        src: /var/lib/jenkins/workspace/assignment-1/docker-compose.yml
        dest: /var/lib/jenkins/workspace/assignment-1/docker-compose.yml
        remote_src: yes  # Use remote_src to indicate that the source file is on the local machine

    - name: Remove existing stack (if any)
      command: "docker stack rm python-flask-stack || true"

    - name: Deploy Docker stack
      command: "docker stack deploy --compose-file /var/lib/jenkins/workspace/assignment-1/docker-compose.yml python-flask-stack"
